/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const UploadLazyImport = createFileRoute('/upload')()
const RateLazyImport = createFileRoute('/rate')()
const AllLazyImport = createFileRoute('/all')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UploadLazyRoute = UploadLazyImport.update({
  path: '/upload',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/upload.lazy').then((d) => d.Route))

const RateLazyRoute = RateLazyImport.update({
  path: '/rate',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/rate.lazy').then((d) => d.Route))

const AllLazyRoute = AllLazyImport.update({
  path: '/all',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/all.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllLazyImport
      parentRoute: typeof rootRoute
    }
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateLazyImport
      parentRoute: typeof rootRoute
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AllLazyRoute,
  RateLazyRoute,
  UploadLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/all",
        "/rate",
        "/upload"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/all": {
      "filePath": "all.lazy.tsx"
    },
    "/rate": {
      "filePath": "rate.lazy.tsx"
    },
    "/upload": {
      "filePath": "upload.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
